name: Deploy
# Controls when the action will run.
on:
    release:
        type: [released]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-20.04
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Deploy using ssh
              uses: actions/setup-go@v2
                  with:
                    go-version: 1.21
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  port: 22
                  script: |
                      cd ~/projects/gotest
                      git pull origin master
                      git status
                      GOOS=linux GOARCH=amd64 go build -o ./build/main .
                      systemctl --user restart gotest
